### ISSUE TITLE
add a channel specifically for 2.6

### ISSUE THREAD

**Issue by wlipa** [ruby/snap.ruby#10]
The only way to get ruby 2.6 via a snap is to install the stable channel, but this would leave the system open to breakage from an unattended major version upgrade.

Please create a 2.6/stable channel so we can control the major release.

    channels:
      stable:        2.6.1 2019-02-05 (128) 25MB classic
      candidate:     ↑                           
      beta:          ↑                           
      edge:          2.6.1 2019-02-03 (128) 25MB classic
      2.5/stable:    2.5.3 2019-02-03 (125) 24MB classic

**Comment by hsbt** [comment]
Now, I created `2.6/stable` track and push 2.6.2 snap.
