### ISSUE TITLE
2.6.3 stable release for armhf

### ISSUE THREAD

**Issue by tobias-grasse** [ruby/snap.ruby#16]
First of all: Thank you for your work! I've just adopted this as a [stage-snap](https://forum.snapcraft.io/t/stage-snaps/11001) in my snap which ships a Rails application for IoT. I was using the ruby plugin before, which meant pulling and building Ruby from source each time I built my snap.

Since my snap is primarily used on armhf devices (Raspberry Pi), I was wondering why the latest 2.6.3 snap for armhf is only available on the edge channel?

**Comment by hsbt** [comment]
Thanks to your kindly reminder. I promoted snaps of all arch to each channel.

Can you try them?

**Comment by tobias-grasse** [comment]
Just tried the 2.6.3 release for armhf, works flawlessly! Thank you!
