### ISSUE TITLE
Bundler 2.0.2 should be default on Ruby 2.6.4, not 1.17.2

### ISSUE THREAD

**Issue by swrobel** [ruby/snap.ruby#17]
```
$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (2.0.2, default: 1.17.2)
```

Why isn't 2.0.2 default?

**Comment by hsbt** [comment]
Because Ruby 2.7 is not released yet.

**Comment by swrobel** [comment]
@hsbt your response doesn't make sense ... this bug was about the Ruby 2.6.4 currently available via snap

**Comment by hsbt** [comment]
Do you understand the `default gem`? The default gem was bumped up with the new version of Ruby. Ruby 2.6 series use only Bundler 1.17.x.
