### ISSUE TITLE
Fix summary on snap website and for `snap info`

### ISSUE THREAD

**Issue by stomar** [ruby/snap.ruby#19]
The snap website (https://snapcraft.io/ruby) still shows an outdated summary:

> Interpreter of object-oriented scripting language Ruby

should be

> Interpreter for the Ruby programming language

as specified in https://github.com/ruby/snap.ruby/blob/master/snap/snapcraft.yaml.

The same applies to the information shown by `snap info ruby`.

**Comment by hsbt** [comment]
Thanks. I fixed it now.
