### ISSUE TITLE
paplay throws error (permission issue)

### ISSUE THREAD

**Issue by Slate5** [ruby/snap.ruby#20]
spawn('paplay foo') throws error:

Connection failure: Connection refused
pa_context_connect() failed: Connection refused

The problem occurs only on Ubuntu 19.10 Gnome shell version 3.34.1

**Comment by hsbt** [comment]
It seems the unrelated issue.

**Comment by Slate5** [comment]
> It seems the unrelated issue.

The important thing is that it works now, there is no more permission issue with ruby from snap when connecting to PulseAudio via paplay. Thank you
