### ISSUE TITLE
2.6.9 stable release for armhf

### ISSUE THREAD

**Issue by tobias-grasse** [ruby/snap.ruby#29]
Hi @hsbt , is it possible to build & release 2.6.9 on the 2.6/stable channel for `armhf` and `arm64`?? I still rely on Ruby 2.6.x for my snap and would like to use the latest patch release as a `stage-snaps` dependency. Thank you in advance!

**Comment by hsbt** [comment]
@tobias-grasse I released 2.6.9 snap package with armhf arch now. Can you try it?
