### ISSUE TITLE
armhf: Publish 2.7.5 on 2.7 track

### ISSUE THREAD

**Issue by tobias-grasse** [ruby/snap.ruby#30]
Hi @hsbt , I noticed that the armhf releases have 2.7.0 on `latest/stable`, and 3.1.0 on `latest/edge`. Is it possible to release the latest 2.7.5 version on the 2.7 track, like you did for the amd64 releases? Please let me know if I can be of any help (testing or something else). If it helps, I have a Raspberry Pi 4 with an LXD snapcraft setup running as a snap builder. And thank you for maintaining the Ruby snap!

**Comment by tobias-grasse** [comment]
I can take a stab at the Rakefile logic to extend it to the supported build architectures, if that helps to automate the build process.

**Comment by hsbt** [comment]
I have only amd64 arch and do sustainable support them. So, `armhf` and other arch is relied on snapcraft build. I can release them manually.

I will investigate to build them with snapcraft build automatically.

**Comment by tobias-grasse** [comment]
I very much appreciate your sustained support for this snap, didn't mean to sound ungrateful 🙂 I know that building snaps for different architectures can get complicated quickly. As long as a build does not take more than 2 hours (or does not need internet access after that time period), the automated [“build from GitHub”](https://snapcraft.io/docs/build-from-github) workflow completely automates building for all supported architectures on native hosts. I'm not 100% sure if that covers the need for different tracks (latest/2.7/2.6), but I can ask the snapcraft team on IRC if you like.

**Comment by hsbt** [comment]
I prepared `remote-build` task like https://github.com/ruby/snap.ruby/blob/master/Rakefile#L17.

So, I could build armhf arch for the all versions of Ruby snap package. Can you try them?
