### ISSUE TITLE
Configure Ruby with option --enable-shared

### ISSUE THREAD

**Issue by arohr** [ruby/snap.ruby#8]
When compiling ruby it should be configured with the option `--enable-shared` [here](https://github.com/ruby/snap.ruby/blob/7e36c7b24be2bb47ef2bcdd384befc01c78f1804/snap/snapcraft.yaml#L54). Some gems with C-extensions need the shared library.

http://www.linuxfromscratch.org/blfs/view/cvs/general/ruby.html

**Comment by hsbt** [comment]
I added it at https://github.com/ruby/snap.ruby/commit/b105e421c0c0df9d23152165f4bab2d961cbe7c9 . The latest versions are provided with its option.
