### ISSUE TITLE
Ruby 2.6.0

### ISSUE THREAD

**Issue by mattbrictson** [ruby/snap.ruby#9]
Will there be a snap released for Ruby 2.6.0?

**Comment by hsbt** [comment]
I've requested `2.6` track in snap store a few days ago.

https://forum.snapcraft.io/t/the-request-for-creating-the-new-track-about-the-ruby-language/9290/2

For now, I can use it. I'm going to publish 2.6 snap in this week.

**Comment by mattbrictson** [comment]
Great news, thank you!

**Comment by mattbrictson** [comment]
Looks like 2.6 is available now. Thanks!
